name: Add Watermark

on:
  push:
    branches:
      - main

jobs:
  add-watermark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add watermark
        run: |
          echo '<div style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); font-size: 48px; color: #f00; opacity: 0.8; z-index: -1; text-align: center; width: 100%;">Rajender Thota</div>' >> sorting-alogorithm-properties.md
